import javax.swing.JSpinner;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;


public class FramePerhitunganHari extends javax.swing.JFrame {

    /**
     * Creates new form FramePerhitunganHari
     */
    public FramePerhitunganHari() {
        initComponents();

        // Isi combo box bulan
        String[] bulan = { "Januari", "Februari", "Maret", "April", "Mei", "Juni",
                           "Juli", "Agustus", "September", "Oktober", "November", "Desember" };
        for (String b : bulan) {
            cmbBulan.addItem(b);
        }

        // Set spinner tahun (range)
        spnTahun.setModel(new javax.swing.SpinnerNumberModel(2025, 1900, 2100, 1));
        ((javax.swing.JSpinner.DefaultEditor) spnTahun.getEditor()).getTextField().setEditable(false);
        // Hilangkan pemisah ribuan pada spinner tahun
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(spnTahun, "0");
        spnTahun.setEditor(editor);
        
        ((JSpinner.DefaultEditor) spnTahun.getEditor()).getTextField().addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != '\b') {
                    e.consume(); // cegah huruf
                }
            }
        });



        txtHasil.setEditable(false);
        txtSelisih.setEditable(false);

        // 🔁 Sinkronisasi combobox & spinner ke JCalendar
        cmbBulan.addActionListener(e -> updateCalendarFromComboAndSpinner());
        spnTahun.addChangeListener(e -> updateCalendarFromComboAndSpinner());

        // 🔁 Sinkronisasi JCalendar ke combobox & spinner
        calendarTanggal.addPropertyChangeListener(evt -> {
            if ("calendar".equals(evt.getPropertyName())) {
                java.util.Calendar cal = calendarTanggal.getCalendar();
                cmbBulan.setSelectedIndex(cal.get(java.util.Calendar.MONTH));
                spnTahun.setValue(cal.get(java.util.Calendar.YEAR));
            }
        });
    }

    // 🔧 Fungsi untuk memperbarui JCalendar dari combo & spinner
    private void updateCalendarFromComboAndSpinner() {
        try {
            int bulan = cmbBulan.getSelectedIndex(); // 0-based
            int tahun = (int) spnTahun.getValue();

            java.util.Calendar cal = java.util.Calendar.getInstance();
            cal.set(java.util.Calendar.YEAR, tahun);
            cal.set(java.util.Calendar.MONTH, bulan);
            cal.set(java.util.Calendar.DAY_OF_MONTH, 1); // default hari pertama

            calendarTanggal.setCalendar(cal);
        } catch (Exception e) {
            System.out.println("Gagal memperbarui JCalendar: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbBulan = new javax.swing.JComboBox<>();
        calendarTanggal = new com.toedter.calendar.JCalendar();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHasil = new javax.swing.JTextArea();
        btnHitung = new javax.swing.JButton();
        lblBulan = new javax.swing.JLabel();
        spnTahun = new javax.swing.JSpinner();
        lblTahun = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSelisih = new javax.swing.JLabel();
        btnSelisih = new javax.swing.JButton();
        dateAkhir = new com.toedter.calendar.JDateChooser();
        dateMulai = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSelisih = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Perhitungan Hari");

        calendarTanggal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        calendarTanggal.setMinimumSize(new java.awt.Dimension(190, 145));
        calendarTanggal.setPreferredSize(new java.awt.Dimension(190, 143));

        btnReset.setText("Reset");
        btnReset.setPreferredSize(new java.awt.Dimension(100, 23));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtHasil.setColumns(20);
        txtHasil.setRows(5);
        jScrollPane1.setViewportView(txtHasil);

        btnHitung.setText("Hitung");
        btnHitung.setPreferredSize(new java.awt.Dimension(100, 23));
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lblBulan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBulan.setText("Pilih Bulan");

        lblTahun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTahun.setText("Masukkan Tahun");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSelisih.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSelisih.setText("Hitung Selisih Hari");

        btnSelisih.setText("Hitung");
        btnSelisih.setPreferredSize(new java.awt.Dimension(100, 23));
        btnSelisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelisihActionPerformed(evt);
            }
        });

        dateAkhir.setPreferredSize(new java.awt.Dimension(150, 30));

        dateMulai.setPreferredSize(new java.awt.Dimension(150, 30));

        txtSelisih.setColumns(20);
        txtSelisih.setRows(5);
        jScrollPane2.setViewportView(txtSelisih);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSelisih)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(dateMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(dateAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnSelisih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(156, 156, 156))))
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelisih)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSelisih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTahun)
                            .addComponent(lblBulan))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(calendarTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendarTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBulan)
                            .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTahun)
                            .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelisihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelisihActionPerformed
        try {
            // Ambil tanggal dari JDateChooser
            java.time.LocalDate pertama = dateMulai.getDate()
                .toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            java.time.LocalDate terakhir = dateAkhir.getDate()
                .toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

            // Validasi input
            if (pertama == null || terakhir == null) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Pilih kedua tanggal terlebih dahulu!");
                return;
            }

            // Hitung selisih hari
            long selisih = java.time.temporal.ChronoUnit.DAYS.between(pertama, terakhir);

            // ✅ Variasi tambahan: tampilkan nama hari pertama & terakhir dalam Bahasa Indonesia
            String hariPertama = pertama.getDayOfWeek()
                .getDisplayName(java.time.format.TextStyle.FULL, new java.util.Locale("id", "ID"));
            String hariTerakhir = terakhir.getDayOfWeek()
                .getDisplayName(java.time.format.TextStyle.FULL, new java.util.Locale("id", "ID"));

            // Format hasil
            String hasil = "Tanggal pertama: " + pertama + " (" + hariPertama + ")\n"
                         + "Tanggal terakhir: " + terakhir + " (" + hariTerakhir + ")\n"
                         + "Selisih hari: " + Math.abs(selisih) + " hari.";

            txtSelisih.setText(hasil);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Terjadi kesalahan! Pastikan kedua tanggal sudah dipilih dengan benar.");
        }
    }//GEN-LAST:event_btnSelisihActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
            // Ambil nilai bulan dan tahun dari input pengguna
            int bulan = cmbBulan.getSelectedIndex() + 1; // index comboBox dimulai dari 0
            int tahun = (int) spnTahun.getValue();

            // Buat objek LocalDate untuk tanggal pertama pada bulan tersebut
            java.time.LocalDate tanggalPertama = java.time.LocalDate.of(tahun, bulan, 1);

            // Dapatkan jumlah hari dalam bulan tersebut
            int jumlahHari = tanggalPertama.lengthOfMonth();

            // Buat objek tanggal terakhir
            java.time.LocalDate tanggalTerakhir = java.time.LocalDate.of(tahun, bulan, jumlahHari);

            // Dapatkan nama hari pertama dan hari terakhir dalam bahasa Indonesia
            String hariPertama = tanggalPertama.getDayOfWeek()
                .getDisplayName(java.time.format.TextStyle.FULL, new java.util.Locale("id", "ID"));
            String hariTerakhir = tanggalTerakhir.getDayOfWeek()
                .getDisplayName(java.time.format.TextStyle.FULL, new java.util.Locale("id", "ID"));

            // Tampilkan hasil lengkap ke txtHasil
            txtHasil.setText(
                "Bulan: " + cmbBulan.getSelectedItem() + " " + tahun + "\n" +
                "Jumlah hari: " + jumlahHari + " hari\n" +
                "Hari pertama: " + hariPertama + " (" + tanggalPertama + ")\n" +
                "Hari terakhir: " + hariTerakhir + " (" + tanggalTerakhir + ")"
            );

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Pastikan bulan dan tahun sudah dipilih dengan benar!");
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        cmbBulan.setSelectedIndex(0);
        spnTahun.setValue(2025);
        txtHasil.setText("");
        dateMulai.setDate(null);
        dateAkhir.setDate(null);
        txtSelisih.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePerhitunganHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSelisih;
    private com.toedter.calendar.JCalendar calendarTanggal;
    private javax.swing.JComboBox<String> cmbBulan;
    private com.toedter.calendar.JDateChooser dateAkhir;
    private com.toedter.calendar.JDateChooser dateMulai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBulan;
    private javax.swing.JLabel lblSelisih;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JSpinner spnTahun;
    private javax.swing.JTextArea txtHasil;
    private javax.swing.JTextArea txtSelisih;
    // End of variables declaration//GEN-END:variables
}
